#
# Executes commands at login pre-zshrc.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

#
# Browser
#

if [[ "$OSTYPE" == darwin* ]]; then
  export BROWSER='open'
fi

#
# Editors
#

export EDITOR='vim'
export VISUAL='vim'
export PAGER='less'

#
# Language
#

if [[ -z "$LANG" ]]; then
  export LANG='en_US.UTF-8'
fi

#
# Paths
#

# Ensure path arrays do not contain duplicates.
typeset -gU cdpath fpath mailpath path

# Set the list of directories that cd searches.
# cdpath=(
#   $cdpath
# )

# Run any external runcom if it exists
if [ -e "$HOME/.zprofile.pre" ]; then
    . "$HOME/.zprofile.pre"
fi

# Add python local path to the PATH
if [ -d "$HOME/.local/bin" ]; then
    PATH="$HOME/.local/bin:$PATH"
fi

# pyenv
export PATH="$HOME/.pyenv/bin:$PATH"
# disable for mac since it causes laggy prompts
if [[ "$OSTYPE" != darwin* ]]; then
    echo "Initiating pyenv"
    eval "$(pyenv init -)"
    eval "$(pyenv virtualenv-init -)"
fi

# Set the list of directories that Zsh searches for programs.
path=(
  $HOME/casey-k/env/bin
  $HOME/casey-env/bin
  $HOME/env/bin
  $HOME/casey-k/installs/bin
  /usr/local/{bin,sbin}
  $path
)

# NVM
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm

# Set the default Less options.
# Mouse-wheel scrolling has been disabled by -X (disable screen clearing).
# Remove -X and -F (exit if the content fits on one screen) to enable it.
export LESS='-F -g -i -M -R -S -w -X -z-4'

# Set the Less input preprocessor.
# Try both `lesspipe` and `lesspipe.sh` as either might exist on a system.
if (( $#commands[(i)lesspipe(|.sh)] )); then
  export LESSOPEN="| /usr/bin/env $commands[(i)lesspipe(|.sh)] %s 2>&-"
fi

# Run any external runcom if it exists
if [ -e "$HOME/.zprofile.post" ]; then
    . "$HOME/.zprofile.post"
fi
