#
# Executes commands at the start of an interactive session.
#
# Authors:
#   Sorin Ionescu <sorin.ionescu@gmail.com>
#

# Hooks for external rc
if [ -e "$HOME/.zshrc.pre" ]; then
    . "$HOME/.zshrc.pre"
fi

# Source Prezto.
if [[ -s "${ZDOTDIR:-$HOME}/.zprezto/init.zsh" ]]; then
  source "${ZDOTDIR:-$HOME}/.zprezto/init.zsh"
fi

# Hooks for external rc
if [ -e "$HOME/.zshrc.post" ]; then
    . "$HOME/.zshrc.post"
fi

